name: Build and deploy documentation

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

# permissions:
#   contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install poetry
        run: python -m pip install poetry==1.3.2 poethepoet==0.10.0

      - name: Install dependencies
        run: poetry install
##

      # - name: Sphinx build
      #   run: |
      #     sphinx-build doc _build
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      #   with:
      #     publish_branch: gh-pages
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: _build/
      #     force_orphan: true