name: Build and deploy documentation

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install poetry
        run: python -m pip install poetry==1.3.2 poethepoet==0.10.0

      - name: Install dependencies
        run: poetry install

      - name: Build docs
        run: |
          cd docs
          poetry run make html

      - uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: .
          if-no-files-found: error

  deploy_docs:
    permissions:
      id-token: 'write'
    runs-on: ubuntu-latest
    needs: docs
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
  
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: github-pages
        path: .
    - name: Display structure of downloaded files
      run: ls -R your/destination/dir
    - uses: actions/configure-pages@v1
    - uses: actions/upload-pages-artifact@v1
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@main
