name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install poetry
        run: python -m pip install poetry==1.1.12 poethepoet==0.10.0

      - name: Install dependencies
        run: poetry install

      - name: Check formatting
        run: poe fmt-test

      - name: Check syntax
        run: poe flake

      - name: Run tests
        run: poe test

      - name: Check type annotations
        run: poe types
